/*
 * Translator Knowledge Beacon Equivalent Concept Clique API
 * This is the Translator Knowledge Beacon \"equivalent concept clique\" web service application programming interface (API).  See the [tk beacon github repo for more information](https://github.com/NCATS-Tangerine/translator-knowledge-beacon/). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: richard@starinformatics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package bio.knowledge.client.api;

import bio.knowledge.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExactmatchesApi
 */
@Ignore
public class ExactmatchesApiTest {

    private final ExactmatchesApi api = new ExactmatchesApi();

    
    /**
     * 
     *
     * Retrieves a list of qualified identifiers of \&quot;exact match\&quot; concepts, [sensa SKOS](http://www.w3.org/2004/02/skos/core#exactMatch) associated with a specified (url-encoded) CURIE (without brackets) concept object identifier,  typically, of a concept selected from the list of concepts originally returned by a /concepts API call on a given KS.  
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getExactMatchesToConceptTest() throws ApiException {
        String conceptId = null;
        List<String> response = api.getExactMatchesToConcept(conceptId);

        // TODO: test validations
    }
    
}
